// <auto-generated />
using System;
using AeroScan.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroScan.API.Migrations
{
    [DbContext(typeof(AeroScanDbContext))]
    partial class AeroScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("AeroScan.API.Models.InspectionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeviationSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("FlatnessErrorMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxDeviationMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinDeviationMm")
                        .HasColumnType("REAL");

                    b.Property<int?>("OutOfToleranceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RmsDeviationMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<double>("ToleranceMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("InspectionSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
