FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["AeroScan.API/AeroScan.API.csproj", "AeroScan.API/"]
COPY ["AeroScan.PointCloud/AeroScan.PointCloud.csproj", "AeroScan.PointCloud/"]
RUN dotnet restore "AeroScan.API/AeroScan.API.csproj"
COPY . .
RUN dotnet publish "AeroScan.API/AeroScan.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "AeroScan.API.dll"]
